### ISSUE TITLE
resup creates temp files in upload source directory.

### ISSUE THREAD

**Issue by meowcat** [eawag-rdm/resup#6]
For `resup put`, resup creates parts-files in a subfolder *of the directory* from where I am uploading. To me this is unexpected, particulary when I'm uploading from a network share. I don't even expect to always have write access to a directory from which I am uploading. Can you use a regular tempdir instead?

**Comment by hvwaldow** [comment]
Valid point. The "standard" temp dirs are problematic for other reasons. But I consider adding an option to allow choosing the directory for operationally required persistence.

**Comment by hvwaldow** [comment]
Option to allow choosing the temp-directory added in fbda0139ebcdcf3aa990f051781579edee093e07 and 67093f25253eb7d8f331e9cce65a7472aa5f492c.
